-   id: prepare-commit-msg-ticket
    name: 'Prepare commit message with ticket ID'
    description: 'Voegt automatisch een ticket-ID (uit de branch-naam) toe aan het commit-bericht.'
    entry: prepare-commit-msg-ticket
    language: python
    stages: [prepare-commit-msg]
    additional_dependencies: [python-dotenv]
    verbose: true