# Dit bestand definieert de hooks die deze repository aanbiedt.

-   id: prepare-commit-msg-ticket
    name: 'Prepare commit message with ticket ID'
    description: 'Automatically adds a ticket ID (from branch name) to the commit message.'
    entry: scripts/prepare_commit_message.py
    language: python
    stages: [prepare-commit-msg]
    additional_dependencies: [python-dotenv]

-   id: validate-commit-msg-ticket
    name: 'Validate commit message for ticket ID'
    description: 'Validates that the commit message contains a valid ticket reference.'
    entry: scripts/validate_commit_message.py
    language: python
    stages: [commit-msg]
    additional_dependencies: [python-dotenv, requests]