-   id: prepare-commit-msg-ticket
    name: 'Prepare commit message with ticket ID'
    description: 'Voegt automatisch een ticket-ID (uit de branch-naam) toe aan het commit-bericht.'
    entry: prepare-commit-msg-ticket
    language: python
    stages: [prepare-commit-msg]
    additional_dependencies: [python-dotenv]
    verbose: true

-   id: validate-commit-msg-ticket
    name: 'Validate commit message for ticket ID'
    description: 'Valideert dat het commit-bericht een geldige ticketreferentie bevat.'
    entry: validate-commit-msg-ticket
    language: python
    stages: [commit-msg]
    additional_dependencies: [python-dotenv, requests]
    verbose: true