repos:
  - repo: local
    hooks:
      - id: prepare-commit-msg-ticket
        name: Prepare commit message with ticket reference
        entry: pdm run scripts/prepare_commit_msg.py
        language: system
        stages: [prepare-commit-msg]
        pass_filenames: true
      - id: commit-msg-ticket-validate
        name: Validate commit message for ticket reference
        entry: pdm run scripts/commit_msg_validate.py
        language: system
        stages: [commit-msg]
        pass_filenames: true 