# .pre-commit-config.yaml

repos:
-   repo: local
    hooks:
    -   id: prepare-commit-msg-ticket
        name: 'Prepare commit message with ticket ID'
        entry: pdm run python scripts/prepare_commit_message.py
        language: system
        stages: [prepare-commit-msg]
        
    -   id: validate-commit-msg-ticket
        name: 'Validate commit message for ticket ID'
        entry: pdm run python scripts/validate_commit_message.py
        language: system
        stages: [commit-msg]