[project]
name = "git-ticket-reference-test"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Collin Aldaibis", email = "caldabis@gmail.com"},
]
dependencies = [
    "requests",
    "python-dotenv",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
