[project]
name = "git-ticket-reference-test"
version = "1.1.3"
description = "Default template for PDM package"
authors = [
    {name = "Collin Aldaibis", email = "caldabis@gmail.com"},
]
dependencies = [
    "requests",
    "python-dotenv",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
prepare-commit-msg-ticket = "scripts.prepare_commit_message:main"
validate-commit-msg-ticket = "scripts.validate_commit_message:main"

[tool.pdm]
distribution = false
